interface tracing {
    use wasi:clocks/wall-clock@0.2.0.{datetime};
    use types.{key-value, instrumentation-scope};

    type trace-id = string;
    type span-id = string;

    flags trace-flags {
        sampled,
    }

    enum span-kind {
        client,
        server,
        producer,
        consumer,
        internal,
    }

    type trace-state = list<tuple<string, string>>;

    /// Options for starting a span.
    record span-options {
        name: string,
        kind: span-kind,
        parent: option<span-context>,
        attributes: list<key-value>,
        start-time: option<datetime>,
        scope: instrumentation-scope,
    }

    /// Identifying trace information for propagation.
    record span-context {
        trace-id: trace-id,
        span-id: span-id,
        trace-flags: trace-flags,
        trace-state: trace-state,
        is-remote: bool,
    }

    variant status {
        unset,
        ok,
        error(string),
    }

    /// Get the currently active span context.
    current-span-context: func() -> span-context;

    /// A live span handle
    resource span {
        /// Create and start a span with the given options.
        constructor(options: span-options);

        /// Get identifying context.
        context: func() -> span-context;

        /// Add attributes
        add-attributes: func(attributes: list<key-value>);

        /// Add a single event
        add-event: func(
            name: string,
            time: option<datetime>,
            attributes: list<key-value>,
        );

        /// Add a link to another span
        add-link: func(
            context: span-context,
            attributes: list<key-value>,
        );

        /// Set status
        set-status: func(status: status);

        /// Update span name (OTEL allows this)
        update-name: func(name: string);

        /// Finish the span
        end: func(end-time: option<datetime>);
    }
}